"""edit refuel record

Revision ID: 10e27b64c1a6
Revises: d7c3605ff91a
Create Date: 2025-10-31 14:15:21.641506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e27b64c1a6'
down_revision: Union[str, Sequence[str], None] = 'd7c3605ff91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refuel_records', 'comment')
    op.drop_column('refuel_records', 'price_per_liter')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refuel_records', sa.Column('price_per_liter', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('refuel_records', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
