"""edit service record

Revision ID: 3986085aae61
Revises: d701656e4add
Create Date: 2025-10-28 12:05:11.211114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3986085aae61'
down_revision: Union[str, Sequence[str], None] = 'd701656e4add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'service_type',
               existing_type=postgresql.ENUM('REPLACEMENT', 'MAINTENANCE', 'DIAGNOSTICS', 'REPAIR', 'BODY_WORK', 'OTHER', name='servicetypeenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'service_type',
               existing_type=postgresql.ENUM('REPLACEMENT', 'MAINTENANCE', 'DIAGNOSTICS', 'REPAIR', 'BODY_WORK', 'OTHER', name='servicetypeenum'),
               nullable=False)
    # ### end Alembic commands ###
