"""add car documents

Revision ID: 3bade3bed184
Revises: 10e27b64c1a6
Create Date: 2025-11-05 14:11:03.933274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bade3bed184'
down_revision: Union[str, Sequence[str], None] = '10e27b64c1a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car_documents',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('vin_number', sa.String(), nullable=True),
    sa.Column('gos_number', sa.String(), nullable=True),
    sa.Column('sts', sa.String(), nullable=True),
    sa.Column('pts', sa.String(), nullable=True),
    sa.Column('insurance_number', sa.String(), nullable=True),
    sa.Column('insurance_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('car_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car_documents')
    # ### end Alembic commands ###
