"""edit service record

Revision ID: 58358fa8de21
Revises: 3986085aae61
Create Date: 2025-10-28 12:40:17.875987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58358fa8de21'
down_revision: Union[str, Sequence[str], None] = '3986085aae61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'total_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_records', 'total_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    # ### end Alembic commands ###
