"""edit service part none price

Revision ID: b79793dde3f2
Revises: 8c816ec975d3
Create Date: 2025-10-29 14:57:40.672526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79793dde3f2'
down_revision: Union[str, Sequence[str], None] = '8c816ec975d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_parts', 'total_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_parts', 'total_price',
               existing_type=sa.NUMERIC(precision=20, scale=2),
               nullable=False)
    # ### end Alembic commands ###
