"""add refuel record

Revision ID: d7c3605ff91a
Revises: bba85b7c3994
Create Date: 2025-10-31 12:15:00.649225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c3605ff91a'
down_revision: Union[str, Sequence[str], None] = 'bba85b7c3994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refuel_records',
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('liters', sa.Float(), nullable=True),
    sa.Column('price_per_liter', sa.Float(), nullable=True),
    sa.Column('fuel_type', sa.Enum('PETROL_92', 'PETROL_95', 'PETROL_98', 'PETROL_100', 'DIESEL', 'GAS', 'ELECTRIC', name='fueltypeenum'), nullable=True),
    sa.Column('gas_station', sa.Enum('LUKOIL', 'ROSNEFT', 'GAZPROMNEFT', 'TATNEFT', 'SHELL', 'BP', 'OTHER', name='gasstationtypeenum'), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('full_tank', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('refuel_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refuel_records')
    # ### end Alembic commands ###
